version: '3.9'
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
