server:
  port: 8085
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/Kity"
    username: "postgres"
    password: "1207"
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5